### ISSUE TITLE
Completely not runnable in VR?

### ISSUE THREAD

**Issue by Dariushuangg** [julienkay/MobileNeRF-Unity-Viewer#12]
Hi, I tried running a basic scene with only the ship model from the original paper in standalone Quest 2, and it crashes my headset (~5fps). Is this normal, or am I missing some setup? I am using URP.

**Comment by julienkay** [comment]
I'm not sure how you're using URP, as the code in this repo only generates shaders for Built-In Render Pipeline, but I've just pushed some changes that make this a lot faster. With the ship scene on my Quest Pro I'm getting around ~45FPS depending on how much screen space it takes up.

Rendering these on a Standalone headset will still be challenging due to the high resolution of the render targets and the heavy per-fragment calculations.
